pipeline {
    agent any

    tools {nodejs "NodeJS"}

    environment {
        PROJECT_PATH="${env.JENKINS_HOME}/workspace/onboarding_3/testing-strategy-3"
        WEB_PATH="${PROJECT_PATH}/web"
        WEB_E2E_PATH="${PROJECT_PATH}/e2e-web"
        SCRIPTS_PATH="${PROJECT_PATH}/scripts"
        DEV="dev"
        ALPHA="alpha"
        PREPROD="preprod"
        PROD="prod"
    }

    stages {
        stage('Audit') {
            steps {
                dir("${SCRIPTS_PATH}") {
                    sh('sh audit.sh')
                }
            }
        }
        stage('Build') {
           steps {
                dir("${WEB_PATH}") {
                    sh """
                    echo "Build"
                    npm i
                    npm start &>/dev/null &
                    """
                }
            }
        }
        stage('Test environment DEV') {
            steps {
                dir("${WEB_E2E_PATH}") {
                   sh """
                    echo "Test"
                    npm i
                    npm run test
                    """
                }
            }
            post {
                always {
                    sh """
                    lsof -ti :3000 | xargs kill &
                    """
                }
            }
        }
        stage('Deployment') {
            steps {
                dir("${SCRIPTS_PATH}") {
                   sh """
                    echo "Deployment"
                    """
                }
            }
        }
    }
}