pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
	stage('Exercise 1') {
	    steps {
		../dojo-2/exercise1.sh
	    }
	}
	stage('Exercise 2') {
	    steps {
		../dojo-2/exercise2.sh
	    }
	}
    }
}
